#!/bin/bash

# =============================================================================
# FormFlow Development Environment Setup Script
# =============================================================================
# Creates a .env.development file with development-ready defaults
# Usage: ./scripts/setup-dev-env.sh
# =============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$PROJECT_ROOT/.env.development"

echo "🐝 FormFlow Development Environment Setup"
echo "=========================================="

# Check if .env.development already exists
if [ -f "$ENV_FILE" ]; then
    read -p "⚠️  .env.development file already exists. Overwrite? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Aborted. Existing .env.development file preserved."
        exit 0
    fi
fi

# Generate random secrets
generate_secret() {
    openssl rand -hex 32 2>/dev/null || cat /dev/urandom | LC_ALL=C tr -dc 'a-zA-Z0-9' | fold -w 64 | head -n 1
}

JWT_SECRET=$(generate_secret)



# Create .env.development file with development defaults
cat > "$ENV_FILE" << EOF
# =============================================================================
# FormFlow Development Environment
# =============================================================================
# Generated by setup-dev-env.sh on $(date)
# =============================================================================

# -----------------------------------------------------------------------------
# Server Configuration
# -----------------------------------------------------------------------------
NODE_ENV=development
DASHBOARD_API_PORT=4000
REDIRECT_URL=http://localhost:4200
DASHBOARD_API_URL=http://localhost:4000

# -----------------------------------------------------------------------------
# Logging Configuration
# -----------------------------------------------------------------------------
LOG_LEVEL=debug
LOG_DIR=logs
LOG_MAX_FILES=14
LOG_SLOW_REQUEST_THRESHOLD=1000
LOG_REQUEST_BODY=true
LOG_RESPONSE_BODY=false
LOG_QUERIES=true
LOG_SLOW_QUERY_THRESHOLD=500
LOG_SAMPLE_RATE=1.0
SERVICE_NAME=
SERVICE_VERSION=

# -----------------------------------------------------------------------------
# Database (PostgreSQL)
# -----------------------------------------------------------------------------
DB_HOST=localhost
DB_PORT=5433
DB_NAME=formflow
DB_USER=formflow
DB_PASSWORD=formflow_dev_password

# -----------------------------------------------------------------------------
# Security (auto-generated - safe for development only)
# -----------------------------------------------------------------------------
JWT_SECRET=${JWT_SECRET}


# -----------------------------------------------------------------------------
# Telegram (optional)
# -----------------------------------------------------------------------------
# TELEGRAM_BOT_TOKEN=



# =============================================================================
# Handler Service Configuration
# =============================================================================

# CORS
ORIGIN=*

# CAPTCHA (auto-generated)


# Email (enabled by default in dev - use Mailpit at localhost:8025)
SYSTEM_MAIL_PROVIDER=localhost
SYSTEM_MAIL_HOST=127.0.0.1
SYSTEM_MAIL_SMTP_PORT=1026
SYSTEM_MAIL_USER=test@localhost
SYSTEM_MAIL_PASSWORD=
SYSTEM_MAIL_TO=test@localhost


# Webhook (optional)
# WEBHOOK_URL=
EOF

echo ""
echo "✅ Created .env.development file with development defaults"
echo ""
echo "📋 Next steps:"
echo "   1. Start the development environment:"
echo "      pnpm dev"
echo ""
echo "   2. Access the services:"
echo "      - Server API:  http://localhost:4000"
echo "      - Handler:     http://localhost:3000"
echo "      - Mailpit UI:  http://localhost:8025"
echo "      - PostgreSQL:  localhost:5433"
echo ""
