#!/bin/bash

# =============================================================================
# FormFlow Development Environment Setup Script
# =============================================================================
# Creates a .env.development file with development-ready defaults
# Usage: ./scripts/setup-dev-env.sh
# =============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$PROJECT_ROOT/.env.development"

echo "🐝 FormFlow Development Environment Setup"
echo "=========================================="

# Check if .env.development already exists
if [ -f "$ENV_FILE" ]; then
    read -p "⚠️  .env.development file already exists. Overwrite? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Aborted. Existing .env.development file preserved."
        exit 0
    fi
fi

# Generate random secrets
generate_secret() {
    openssl rand -hex 32 2>/dev/null || cat /dev/urandom | LC_ALL=C tr -dc 'a-zA-Z0-9' | fold -w 64 | head -n 1
}

JWT_SECRET=$(generate_secret)
ENCRYPTION_KEY=$(generate_secret)
HMAC_SECRET=$(generate_secret)

# Create .env.development file with development defaults
cat > "$ENV_FILE" << EOF
# =============================================================================
# FormFlow Development Environment
# =============================================================================
# Generated by setup-dev-env.sh on $(date)
# =============================================================================

# -----------------------------------------------------------------------------
# Server Configuration
# -----------------------------------------------------------------------------
NODE_ENV=development
PORT=3000
REDIRECT_URL=http://localhost:4200
DASHBOARD_API_URL=http://localhost:3000
EMAIL_USER=test@localhost

# -----------------------------------------------------------------------------
# Logging Configuration
# -----------------------------------------------------------------------------
LOG_LEVEL=debug
LOG_DIR=logs
LOG_MAX_FILES=14
LOG_SLOW_REQUEST_THRESHOLD=1000
LOG_REQUEST_BODY=true
LOG_RESPONSE_BODY=false
LOG_QUERIES=true
LOG_SLOW_QUERY_THRESHOLD=500
LOG_SAMPLE_RATE=1.0
SERVICE_NAME=
SERVICE_VERSION=

# -----------------------------------------------------------------------------
# Database (PostgreSQL)
# -----------------------------------------------------------------------------
DB_HOST=localhost
DB_PORT=5433
DB_NAME=formflow
DB_USER=formflow
DB_PASSWORD=formflow_dev_password

# -----------------------------------------------------------------------------
# Security (auto-generated - safe for development only)
# -----------------------------------------------------------------------------
JWT_SECRET=${JWT_SECRET}
ENCRYPTION_KEY=${ENCRYPTION_KEY}

# -----------------------------------------------------------------------------
# GitHub OAuth (required for login - get from GitHub Developer Settings)
# -----------------------------------------------------------------------------
# Create an OAuth App at: https://github.com/settings/developers
# Set callback URL to: http://localhost:3000/auth/github/callback
GITHUB_CLIENT_ID=
GITHUB_CLIENT_SECRET=

# -----------------------------------------------------------------------------
# Gmail OAuth2 (optional - for sending emails)
# -----------------------------------------------------------------------------
# GMAIL_CLIENT=
# GMAIL_SECRET=
# GMAIL_EMAIL=
# GMAIL_REFRESH=
# GMAIL_ACCESS=

# -----------------------------------------------------------------------------
# Stripe (optional - for payments)
# -----------------------------------------------------------------------------
# STRIPE_TEST_KEY=
# STRIPE_WHSEC=

# -----------------------------------------------------------------------------
# Telegram (optional)
# -----------------------------------------------------------------------------
# TELEGRAM_API_TOKEN=

# -----------------------------------------------------------------------------
# Google OAuth (optional - for custom return emails)
# -----------------------------------------------------------------------------
# GOOGLE_CLIENT_ID=
# GOOGLE_CLIENT_SECRET=

# =============================================================================
# Handler Service Configuration
# =============================================================================

# CORS
ORIGIN=*

# CAPTCHA (auto-generated)
HMAC=${HMAC_SECRET}

# Email (disabled by default in dev - use Mailpit at localhost:8025)
# EMAIL_PROVIDER=localhost
# SMTP_PORT=1025
# EMAIL_USER=test@localhost
# EMAIL_PASSWORD=
# EMAIL_TO=test@localhost
# GMAIL_TRUE=False

# Webhook (optional)
# WEBHOOK_URL=
EOF

echo ""
echo "✅ Created .env.development file with development defaults"
echo ""
echo "📋 Next steps:"
echo "   1. Set up GitHub OAuth (required for login):"
echo "      - Go to: https://github.com/settings/developers"
echo "      - Create OAuth App with callback: http://localhost:3000/auth/github/callback"
echo "      - Add GITHUB_CLIENT_ID and GITHUB_CLIENT_SECRET to .env.development"
echo ""
echo "   2. Start the development environment:"
echo "      npm run dev"
echo ""
echo "   3. Access the services:"
echo "      - Server API:  http://localhost:3000"
echo "      - Handler:     http://localhost:3001"
echo "      - Mailpit UI:  http://localhost:8025"
echo "      - PostgreSQL:  localhost:5433"
echo ""
